Fix test flakyness by waiting to see the kubeconfig
The secret needs to be in place BEFORE attempting to get the child cluster client.

Currently some of the tests are flaky with:
```
    basic_test.go:78:
        	Error Trace:	/home/runner/work/k0smotron/k0smotron/inttest/basic/basic_test.go:78
        	Error:      	Received unexpected error:
        	            	secrets "kmc-test-kubeconfig" not found
        	Test:       	TestBasicSuite/TestK0sGetsUp
```

Signed-off-by: Jussi Nummelin <jnummelin@mirantis.com>